"""intial migration

Revision ID: c5e8db2650bc
Revises: 
Create Date: 2022-11-16 14:36:58.624678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5e8db2650bc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Dish',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ingredient_Category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Ingredient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['Ingredient_Category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Dish_Ingredients',
    sa.Column('dish_id', sa.Integer(), nullable=False),
    sa.Column('ingredient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dish_id'], ['Dish.id'], ),
    sa.ForeignKeyConstraint(['ingredient_id'], ['Ingredient.id'], ),
    sa.PrimaryKeyConstraint('dish_id', 'ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Dish_Ingredients')
    op.drop_table('Ingredient')
    op.drop_table('Ingredient_Category')
    op.drop_table('Dish')
    # ### end Alembic commands ###
